### ISSUE TITLE
Missing Setting EnableSssItemLevelMonitoring

### ISSUE THREAD

**Issue by clintwar** [seanmcne/OrgDbOrgSettings#11]
The setting EnableSssItemLevelMonitoring is missing and is available as of 9.0.2.193.

It is a boolean and the default is false.

**Comment by seanmcne** [comment]
Added it quick - haven't fully tested the build yet so I just published it as a pre-release: https://github.com/seanmcne/OrgDbOrgSettings/releases/tag/v1.0.1806.08
