### ISSUE TITLE
DoNotAutotrackEmail setting affects personal setting no email messages

### ISSUE THREAD

**Issue by meetse** [seanmcne/OrgDbOrgSettings#112]
Hi,

Have you noticed that if you turn DoNotAutotrackEmailin option to true and revert back to false, personal setting no email messages disappears?

[Personalsettings.docx](https://github.com/seanmcne/OrgDbOrgSettings/files/13434383/Personalsettings.docx)
Do you happen to know how to get that setting back?

**Comment by seanmcne** [comment]
I don't have a recent personal experience with this setting but I'll refer back to the KB - the KB seems to indicate: 
- True: The option "No Email Messages" becomes an option in the dropdown 
- False: There is *not* an option of "No Email Messages" in the dropdown 

Given the KB and the way it's written, I'd expect the option to appear when the setting is 'true' and the option to disappear when the setting is 'false', and I would hope the option would come back if set to 'true' again. 

https://support.microsoft.com/en-us/topic/orgdborgsettings-tool-for-microsoft-dynamics-crm-20a10f46-2a24-a156-7144-365d49b842ba

![image](https://github.com/seanmcne/OrgDbOrgSettings/assets/2292260/57a384f2-0e38-4e84-a4e7-d00b53a07aad)

If this isn't working as expected, I might suggest to contact support to find out if there was a change in the intent or functionality of this setting.
