### ISSUE TITLE
Document Location Settings

### ISSUE THREAD

**Issue by ryncdr** [seanmcne/OrgDbOrgSettings#127]
Not an issue, but a question:
Is there a setting to control the automatic naming of Document Locations similar to _CreateSPFoldersUsingNameandGuid_?
This setting controls the names of the folders in SharePoint, I'm looking for what populates the display names of the records in the entity (e.g. 'Documents on MySite 1').
[What happens when you navigate to the Documents tab first time?](https://learn.microsoft.com/en-us/dynamics365/customerengagement/on-premises/basics/manage-sharepoint-documents-document-locations-in-dynamics-365-apps?view=op-9-1#what-happens-when-you-navigate-)

**Comment by seanmcne** [comment]
Hi @ryncdr - I am not aware of a setting like that, it might be worth opening a case to see if they know of one and if there isn't, seeing if one could be requested (there may be something to vote on in a feedback forum as well).

**Comment by ryncdr** [comment]
That's what I expected. I appreciate your expertise, thank you!
