### ISSUE TITLE
Error after updating the solution

### ISSUE THREAD

**Issue by Ruderg** [seanmcne/OrgDbOrgSettings#129]
We've handled an error, for reference the error info is:
Name:ReferenceError
Message:WindowsAzure is not defined
Description:Error Description Is Null
stack:ReferenceError: WindowsAzure is not defined at HTMLDocument. (https://xxx//WebResources/mspfedyn_/orgdborgsettings/orgdborgsettings.html:1246:52) at e (https://xxx/_static/_common/scripts/jquery-3.6.0.min.js?ver=-585237973:1548:47) at t (https://xxx/_static/_common/scripts/jquery-3.6.0.min.js?ver=-585237973:1557:37)
Click a setting row for more details at the bottom of the page. NOTE: you should not change any setting without having a specific reason to do so.

**Comment by seanmcne** [comment]
@Ruderg it appears Azure made an update which deprecated some of the legacy azure mobile API's used to check for newer solution updates (which will impact all versions).  The good news is, you can ignore the message and it won't make any functionality impact and I'll look to see how to update the javascript SDK for a future build.  Thanks for the heads up!

**Comment by Ruderg** [comment]
Hello Sean,

great job! 😊
It works now.

Thank you very much!

Freundliche Grüße / Best regards

Gabriele Ruder
IT Consultant
Corporate IT Services
___________________________________

Herrenknecht AG
Schlehenweg 2
77963 Schwanau-Allmannsweier
Deutschland
Tel: +49 7824 302 3723

***@***.***
http://www.herrenknecht.de<http://www.herrenknecht.de/>



Registergericht / Registration Court: Freiburg HRB 390485
Aufsichtsrat/Supervisory Board:
Dr.-Ing. Bertram Kandziora, Vorsitzender / Chairman
Günther H. Oettinger, Stellvertreter/Vice Chairman
Vorstand / Board of Management:
Dr.-Ing. E.h. Martin Herrenknecht, Vorsitzender/Chairman
Dipl.-Wi.-Ing. Michael Sprang, Stellvertreter/Vice Chairman, CFO
Dipl.-Ing. (FH) Ulrich Schaffhauser
Dipl.-Ing. (FH) Martin-Devid Herrenknecht

Weitere Informationen zum Datenschutz finden Sie unter https://www.herrenknecht.com/de/footer/datenschutz/

For more information about data protection, please check https://www.herrenknecht.com/en/footer/privacy-policy/



Von: Sean McNellis ***@***.***>
Gesendet: Dienstag, 27. August 2024 00:36
An: seanmcne/OrgDbOrgSettings ***@***.***>
Cc: Ruder, Gabriele ***@***.***>; Mention ***@***.***>
Betreff: Re: [seanmcne/OrgDbOrgSettings] Error after updating the solution (Issue #129)

WARNING: This is an external e-mail from outside the company!

Do not open or click links and attachments unless you recognize the sender and know the content is safe.


Closed #129<https://github.com/seanmcne/OrgDbOrgSettings/issues/129> as completed via #130<https://github.com/seanmcne/OrgDbOrgSettings/pull/130>.
