### ISSUE TITLE
TrackCategorizedItems does not seem to work

### ISSUE THREAD

**Issue by KLTechy** [seanmcne/OrgDbOrgSettings#20]
Hi Sean, thank you for providing this solution to automate enabling the org settings!

I've imported your latest solution 9/4, enabled TrackCategorizedItems setting and published the changes to my CRM sandbox instance.  However, from Outlook I do not see the "Tracked to Dynamics 365 CRM" category.  I wonder if other admins who are trying to deploy this feature are facing the same issue.  I tried manually creating that category in my Outlook client and assigning an email to that category.  After waiting 15 minutes for the sync to D365, that email is still not tracked.  

I just want to submit my test case in case you or others have suggestions on further instructions to get this feature working completely.  I've also tried tracking an email using App for Outlook, and the The Tracked to Dynamics 365 category is not even assigned.

**Comment by seanmcne** [comment]
If the setting is enabled and the feature isn’t working I’d suggest opening a case after double checking the feature documentation - https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/use-outlook-category-track-appointments-emails
