### ISSUE TITLE
MakeSocialPanePhoneCallCompleted is missing

### ISSUE THREAD

**Issue by Kdjacques** [seanmcne/OrgDbOrgSettings#23]
I just downloaded this latest version then imported in my 2016 environment and I do not see the option to make social pane phone call completed.

**Comment by seanmcne** [comment]
What’s your org version?  It will display in version 8.1.1.? Up through all of v9.

**Comment by Kdjacques** [comment]
My org version is 8.1.359

**Comment by seanmcne** [comment]
Ok that makes sense - this setting is only available from 8.1.1.915 and higher.

**Comment by Kdjacques** [comment]
Thank you for the update.
