### ISSUE TITLE
OrgDBOrgsetting Missing IsSOPIntegrationEnabled 

### ISSUE THREAD

**Issue by rykema** [seanmcne/OrgDbOrgSettings#29]
Sean - great utility!  Noticed one setting we have to change time to time using an integration tool or custom code.  It's called IsSOPIntegrationEnabled.  It's been around since CRM 2011 but no interface to change it.  It would be handy to turn on or off using your tool.

**Comment by seanmcne** [comment]
Thanks for reaching out - this setting isn't actually an OrgDbOrgSetting, however it is an organization attribute which I also have in the editor (for things like export to excel and resetting the yammer fields, etc).  Let me look into this, I should be able to quickly add it in if you have a need to change the value.  The more difficult part is going to be coming up with the documentation for it.

**Comment by seanmcne** [comment]
Released via PR #30
