### ISSUE TITLE
Unable to import due to the attached error message

### ISSUE THREAD

**Issue by TapsiL** [seanmcne/OrgDbOrgSettings#36]
![image](https://user-images.githubusercontent.com/51069115/58395729-3aa98900-807c-11e9-8fda-fb2516f0fec1.png)

![image](https://user-images.githubusercontent.com/51069115/58395606-af2ff800-807b-11e9-978a-e54e6f914e69.png)

![image](https://user-images.githubusercontent.com/51069115/58395637-ddadd300-807b-11e9-90e4-2c52cdeac0fb.png)

Hello, 

I am unable to import the the solution package, we are using CRM on-prem , Attached images of the solution used, error received and our current CRM version. 

Please advise if I am missing anything. Thanking you.

Regards,
Tapsi

**Comment by seanmcne** [comment]
Hi Tapsi, you’ll have to use an old release that still supports v7.0 (2015). All the latest releases only support v8.0+. 

This previous release should work for you: https://github.com/seanmcne/OrgDbOrgSettings/releases/tag/v1.0.1606.08
