### ISSUE TITLE
TrackAppointmentsFromNonOrganizer doesnt work

### ISSUE THREAD

**Issue by runedaub** [seanmcne/OrgDbOrgSettings#39]
The new "TrackAppointmentsFromNonOrganizer" doesnt work in release 1.0.1905.3003 . Throws an error when trying to click ADD.
We've handled an error, for reference the error info is:
Name:Error Name Is Null
Message:Error Message Is Null
Description:Error Description Is Null
stack:Stack is Null

CRM Online version: 9.1.0.5228

**Comment by seanmcne** [comment]
I just checked this in Canary and in our other regions with newer updates and it's working.  I'm not sure if this is a specific issue in the current NAM build but I do know there was a spelling change at one point and it might not yet be in NAM.  I hope this next round of builds will allow you to set it again.

**Comment by lauramortick** [comment]
@seanmcne what do you mean by "NAM"? We are on Version 1710 (9.1.0.5229).  thanks! Laura

**Comment by seanmcne** [comment]
Sorry for the acronym 😀 NAM stands for North America.

**Comment by lauramortick** [comment]
Ha ha! I should have known! Thanks @seanmcne!

**Comment by runedaub** [comment]
We are now on 9.1.0.5825 and still recieving the following error:
We've handled an error, for reference the error info is:
Name:Error Name Is Null
Message:Error Message Is Null
Description:Error Description Is Null
stack:Stack is Null

Our environment is on crm4 (EMEA).
Guess I need to contact MS for info on when they are releasing support for TrackAppointmentsFromNonOrganizer on EMEA.

**Comment by seanmcne** [comment]
Hi - I just tested in the northamerica region on build# 5626. I can try spinning up an emea org and testing as well here as your build should now have that setting in it. 

![image](https://user-images.githubusercontent.com/2292260/60114311-3767f280-9739-11e9-8c66-2e1ce7b32c59.png)

**Comment by runedaub** [comment]
Microsoft confirms it works on emea vanilla organizations.. but I have now tested it on 3 individual upgraded customers organizations and it is not working.. microsoft hopes it should be patched by this mondays release package.

**Comment by seanmcne** [comment]
Upon an initial quick look, I'm not able to set this value in EMEA or GBR either even on the same or a build in advance of yours and what's in NAM.  I actually cannot create this setting in a vanilla emea organization - i wonder if it is a build issue specifically for this version. Please keep me updated as I have brand new GBR and EMEA orgs up and running as a test and can't create them (in vanilla instances).

**Comment by runedaub** [comment]
I will keep you in the loop

**Comment by runedaub** [comment]
I dont see how to PM you in here.. so sending you info on linkedin

**Comment by NatashaS25** [comment]
Hi Sean, this is not working for me either with the latest release. Based in UK and using CRM4.dynamics.com region. Any news in getting this working? Same error as rune i'm afraid.

**Comment by runedaub** [comment]
Hey Sean... My support ticket is: 119062522000248.. Being handled by Martin Draganov.

**Comment by seanmcne** [comment]
Ok finally got it figured out!  Thanks for your patience, the latest release should resolve the issue.  Thanks again! 

https://github.com/seanmcne/OrgDbOrgSettings/releases/tag/v1.0.1907.0802
