### ISSUE TITLE
Future MS CRM Deprecations and your product functioning

### ISSUE THREAD

**Issue by MMlinsek** [seanmcne/OrgDbOrgSettings#40]
Hello,

We are using your product Organization Settings Editor in Microsoft Dynamics CRM. Microsoft announced some deprecations coming out with new major release , so I want to check by you if they will affect to product functioning. URL to MS article: https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/important-changes-coming
Do you intend to upgrade code for this product to be compliant with latest CRM release? We want to assure that all your solutions will working OK after CRM upgrade.

Probably my questions currently aren't an issue, but they could happen in future. :)

Thank you in advance. Best Regards,

Matej

**Comment by seanmcne** [comment]
Hi Matej, this is just a simple html webresource that allows you to easily edit settings that might help enable, disable, or alter certain functions that have been introduced to the product without an in-box editor.  The entire editor itself just reads/writes to the CRM WebApi, I do not anticipate any compatibility problems as it's using a recent webapi version. Thanks for the question and hopefully this has helped you save some time!
