### ISSUE TITLE
Add 'HideTrackAllOption' Error

### ISSUE THREAD

**Issue by hath000** [seanmcne/OrgDbOrgSettings#42]
When Adding 'HideTrackAllOption' we are given the following error and do not get the edit option for that setting.  The other setting we changed (AutoCreateContactOnPromote) threw a similar error but still seems to have worked.  We're OnPrem IFD deployed on version 9.0.6.9.

We've handled an error, for reference the error info is:
Name:Error
Message:There was an error updating your orgDBOrgSettings: undefined
Description:There was an error updating your orgDBOrgSettings: undefined
stack:Stack is Null

**Comment by seanmcne** [comment]
Could you grab a fiddler trace or network trace of the request/response and show me the request & response (please exclude any auth headers).  

I would expect to see a request of the following to the URL containing "https://serverurl/api/data/v9.0/organizations({orgid})" 

And a payload of: 
```json
{"orgdborgsettings": "<OrgSettings><HideTrackAllOption>false</HideTrackAllOption></OrgSettings>"}
```

If you're seeing an error, you'll likely get some kind of response detail.  I have confirmed the most recent versions of D365 online do work with the setting, hopefully the request/response will help shed light on what might be going on. 

Two more questions: 
1. Are you able to add other settings?  If not, try accessing via the ad auth url 
2. Are you running the latest release of the tool/editor?

**Comment by hath000** [comment]
Sean,

Thank you for the response.  I am using version 1.0.1907.0802 of the tool.  I’ve tried on environments running Update .6 as well as update .8 - both have this same issue.  Some settings work but others do not.  Below is a list of settings that do not work.  When they fail, I’m presented the highlighted error.  Fiddler Request/Response are listed below for both a working setting as well as one that fails.

FYI -  I also have an open case with Microsoft as the OrgDBOrgSettings tool they ship is unable to connect to any on-prem v9 IFD deployed environment (SR: 119082924005113).  Microsoft has confirmed there is an issue with their tool (they can recreate the issue in their lab) and had recommended your tool as an alternative while they continue to investigate the issues with the OrgDBOrgSettings tool.

Settings that Error:
EnableViewSelectorForEmailTemplatesInPersonalOptionsDialog
ExchangeSyncIdMappingPersistenceTimeInDays
HideTrackAllOption
IgnoreConversationIndexAndInReplyToForCorrelation
MaximumSubjectLengthOnMailServer
ResolveForInactiveEntities
TrackAppointmentsFromNonOrganizer
UseFilteringMethodOfSyncingMailboxOnlyForCorrelation

Error when Adding setting fails:
We've handled an error, for reference the error info is:
Name:Error
Message:There was an error updating your orgDBOrgSettings: undefined
Description:Error Description Is Null
stack:Error: There was an error updating your orgDBOrgSettings: undefined at Object.error (https://crmdev02.opus-group.com/DEV02/WebResources/mspfedyn_/orgdborgsettings/orgdborgsettings.html:191:40) at j (https://crmdev02.opus-group.com/_static/_common/scripts/jquery-2.1.1.min.js?ver=1436446892:1417:29) at Object.fireWith [as rejectWith] (https://crmdev02.opus-group.com/_static/_common/scripts/jquery-2.1.1.min.js?ver=1436446892:1467:104) at x (https://crmdev02.opus-group.com/_static/_common/scripts/jquery-2.1.1.min.js?ver=1436446892:3385:605) at XMLHttpRequest. (https://crmdev02.opus-group.com/_static/_common/scripts/jquery-2.1.1.min.js?ver=1436446892:3555:96)

Fiddler logs:

Successful Setting
Request:
PATCH https://crmdev02.opus-group.com/dev02/api/data/v8.0/organizations(035d1c0c-96fe-4b7a-892d-5168c646d377) HTTP/1.1
Host: crmdev02.opus-group.com
Connection: keep-alive
Content-Length: 108
OData-Version: 4.0
Origin: https://crmdev02.opus-group.com<https://crmdev02.opus-group.com/>
OData-MaxVersion: 4.0
Sec-Fetch-Mode: cors
Content-Type: application/json; charset=UTF-8
Accept: application/json
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Sec-Fetch-Site: same-origin
Referer: https://crmdev02.opus-group.com/DEV02/WebResources/mspfedyn_/orgdborgsettings/orgdborgsettings.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: Removed for security

{"orgdborgsettings":"<OrgSettings><ReassignAllExtendedTimeout>0</ReassignAllExtendedTimeout></OrgSettings>"}

Response:
HTTP/1.1 204 No Content
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: https://crmdev02.opus-group.com/dev02/api/data/v8.0/organizations(035d1c0c-96fe-4b7a-892d-5168c646d377)
Server:
x-ms-service-request-id: 4dc933df-ab13-4136-a256-b049d58f24c8
REQ_ID: 4dc933df-ab13-4136-a256-b049d58f24c8
OData-Version: 4.0
OData-EntityId: https://crmdev02.opus-group.com/dev02/api/data/v8.0/organizations(035d1c0c-96fe-4b7a-892d-5168c646d377)
x-ms-ratelimit-burst-remaining-xrm-requests: 59989
Access-Control-Expose-Headers: Preference-Applied,OData-EntityId,Location,ETag,OData-Version,Content-Encoding,Transfer-Encoding,Content-Length,Retry-After
x-ms-ratelimit-time-remaining-xrm-requests: 1,799.42
Date: Wed, 11 Sep 2019 13:14:21 GMT


Failed Setting:
Request:
PATCH https://crmdev02.opus-group.com/dev02/api/data/v8.0/organizations(035d1c0c-96fe-4b7a-892d-5168c646d377) HTTP/1.1
Host: crmdev02.opus-group.com
Connection: keep-alive
Content-Length: 96
OData-Version: 4.0
Origin: https://crmdev02.opus-group.com<https://crmdev02.opus-group.com/>
OData-MaxVersion: 4.0
Sec-Fetch-Mode: cors
Content-Type: application/json; charset=UTF-8
Accept: application/json
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Sec-Fetch-Site: same-origin
Referer: https://crmdev02.opus-group.com/DEV02/WebResources/mspfedyn_/orgdborgsettings/orgdborgsettings.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: Removed for security

{"orgdborgsettings":"<OrgSettings><HideTrackAllOption>false</HideTrackAllOption></OrgSettings>"}

Response:
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; odata.metadata=minimal
Expires: -1
Server:
x-ms-service-request-id: 8381506f-c8b7-4d3e-b489-4dbe0d68b6c1
REQ_ID: 8381506f-c8b7-4d3e-b489-4dbe0d68b6c1
REQ_ID: 8381506f-c8b7-4d3e-b489-4dbe0d68b6c1
x-ms-ratelimit-burst-remaining-xrm-requests: 59988
Access-Control-Expose-Headers: Preference-Applied,OData-EntityId,Location,ETag,OData-Version,Content-Encoding,Transfer-Encoding,Content-Length,Retry-After
x-ms-ratelimit-time-remaining-xrm-requests: 1,799.40
OData-Version: 4.0
Date: Wed, 11 Sep 2019 13:15:16 GMT
Content-Length: 3018

{"error":{"code":"0x80048514","message":"Invalid Organization Setting passed in. Please check the datatype and pass in an appropriate value.","innererror":{"message":"Invalid Organization Setting passed in. Please check the datatype and pass in an appropriate value.","type":"System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]","stacktrace":"   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Upsert(Entity entity)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Update(Entity entity, UpdateOption updateOption)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.UpdateEdmEntity(CrmODataExecutionContext context, String edmEntityName, String entityKeyValue, EdmEntityObject entityObject)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityImplementation(String& entityName, String key, EdmEntityObject entityDelta)\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}}}


Thank you,
Steve

**Comment by seanmcne** [comment]
I'm sorry this has been an issue for you. The only thing I see that's a little fishy here is the version # of the webapi being used, it's falling back to v8.0 which is odd.  I would expect it to detect v9 and use that instead, however, if other settings work then this likely isn't related to the version of the webapi.  It's unlikely that this is the problem, but you could use fiddler to recompose one of the patch requests and play it back using the v9.0 or v9.1 webapi to see if it goes through. 

Regarding the settings, each specific binary version of CDS will have certain coded (in the code itself) orgdborgsettings that are valid for that version - some settings are added and some can be removed based on the build.  Most likely, the build of onprem d365 you're using is missing these particular settings listed above, for some reason or another, or the setting value you're passing in for it isn't recognized. 

I would expect support to be able to help you with this - they can use the tool they provide or you could use powershell or a simple console app to also push these simple data value updates to reproduce the problem.
