### ISSUE TITLE
Source Code for Dynamics CRM 2013 is missing. Would you please provide the link to download it.

### ISSUE THREAD

**Issue by nkhalife** [seanmcne/OrgDbOrgSettings#48]

**Comment by seanmcne** [comment]
Do you mean the managed solution compatible with v6?

**Comment by nkhalife** [comment]
Thank you for your prompt response. I thought for v6 there is only the standalone executable tool (**CrmJobEditor)** and this what I was looking for to make some changes to the tool to enable the Audit Partition. If it is not available I will try using the managed solution to see if it helps.
