### ISSUE TITLE
Settings not updated and error message

### ISSUE THREAD

**Issue by Ciolin** [seanmcne/OrgDbOrgSettings#5]
Hi Sean,

I'm facing an issue with OrgDbOrgSettings. 
If I try to edit a setting (maxrecordsforexporttoexcel, for instance) I get the following message : 
We've handled an error, for reference the error info is : 
Name : Error Name is Null
Message : Error Message is Null
Description : Error Description is Null
stack : Stack is Null
I have several organizations and only have this issue on 1 org.
Solution import worked fine on that org. 
Dynamics CRM is 2015 Onpremises UR 0.2 (7.0.2 53)
Do you have any idea why I get this error and how I could make it work ?

Thank you 
Regards
Loïc

**Comment by seanmcne** [comment]
I've seen this once before a long while ago, are you using the older version that works with CRM 2015 or one of the newer versions?  If an older one, which version are you running?   Are you able to try debugging the javascript to see where it's failing?

**Comment by Ciolin** [comment]
Hi Sean,

The org where I had an error was "corrupted" (and was not reflecting Prod environment).
So everything worked fine at the end.
Regards

**Comment by seanmcne** [comment]
thank you for the update!
