### ISSUE TITLE
EnableTDSEndpoint Setting

### ISSUE THREAD

**Issue by DREWLFE** [seanmcne/OrgDbOrgSettings#52]
I can't see EnableTDSEndpoint in the list of settings for my org, is that because I need to wait for the org to update or does it need to be added to the settings editor?

https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi

**Comment by abhiseksinhaGIT** [comment]
@seanmcne  - OrgDBOrgSettingsTool is back in high demand with everyone trying out TDS endpoint for CDS. Please update the settings.xml for us lazies! :)

**Comment by seanmcne** [comment]
Yep it’s already in the tooling - but you’ll need a build of CDS that supports it - depending on your Geography, your environment will hopefully support it soon.

**Comment by abhiseksinhaGIT** [comment]
I enabled TDS endpoint for my org using the traditional OrgDbOrgSettingsTool.exe and I do see that the settings.xml in your latest build does have the entry for EnableTDSEndpoint. But I see the minversion for that is 9.1.0.17427, my org is 9.1.0.17162. Not sure why there is a disconnect.

**Comment by seanmcne** [comment]
9.1.0.17427 was an educated guess, based on the builds that were rolling out.  I can update to your existing version (17162) but i suspect it might not work for everyone like it has for you.

**Comment by Sinha-Abhisek** [comment]
Unless you have insider information that it will work for all in 17162, I would say you leave it as-is. Thanks for looking into it.

**Comment by seanmcne** [comment]
Give this one a try: #54

**Comment by Sinha-Abhisek** [comment]
I see it now. Thank you! 👍

**Comment by DREWLFE** [comment]
"Verify that your environment has at least version 9.1.0.17437"
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/view-entity-data-power-bi

So that's where it is in the docs and the educated guess was correct
