### ISSUE TITLE
XrmToolBox tool for OrgDbOrgSettings [enhancement]

### ISSUE THREAD

**Issue by LinnZawWin** [seanmcne/OrgDbOrgSettings#55]
It would be great to have OrgDbOrgSettings as one of the tools in XrmToolBox which would allow the user to connect to the organisation and update the settings. (without the need to install the managed solution zip file)

**Comment by seanmcne** [comment]
Thanks for the feedback!  As of right now I don't have the capacity to change a lightweight webgui over to a winforms ui.  For now I foresee it staying as a lightweight managed solution - if you are running into difficulties let me know and I can try to address them. Thx!
