### ISSUE TITLE
Installed and changed a value, but doesnt seem to make a difference

### ISSUE THREAD

**Issue by AzureAzim** [seanmcne/OrgDbOrgSettings#56]
Hello, I am trying to change the value for MaxRecordsForExportToExcel  to a lower number (such as 1).

I was able to modify the package and import, then set the value for MaxRecordsForExportToExcel  to 1, but i can still export greater than one. Not sure if this attribute is only valid for Dynamics on premises and not Online.

**Comment by seanmcne** [comment]
@AzureAzim, it is possible there is a lower bound/limit where 1 won't be taken as a valid value, it almost appears as if 10,000 might be the minimum value accepted (it ignores values below that). Are you seeing 10K still coming out even when it's set to 1?

**Comment by seanmcne** [comment]
@AzureAzim - I don't believe you can set it below the default minimum value (for that particular setting, it's Organization.MaxRecordsForExportToExcel).
