### ISSUE TITLE
Support for pastexpansionwindow

### ISSUE THREAD

**Issue by harryepstein** [seanmcne/OrgDbOrgSettings#59]
Is this attribute (column) still supported and will you be adding it in the future?

**Comment by seanmcne** [comment]
This is an organization attribute as opposed to an orgdborgsetting but I can certainly add this (there is a section of settings that are just organization attributes which might frequently need to be changed or viewed).

**Comment by seanmcne** [comment]
Documentation link: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/organization?view=dynamics-ce-odata-9
