### ISSUE TITLE
OrgDBOrgSetting Missing TrackCategorizedItems

### ISSUE THREAD

**Issue by justinwkruse** [seanmcne/OrgDbOrgSettings#7]
Sean, thanks so much for this awesome little utility.

The D365 team yesterday just announced this feature:  https://blogs.msdn.microsoft.com/crm/2018/05/02/introducing-outlook-category-based-tracking-in-server-side-synchronization/

In order to facilitate this, you need onfigure category-based tracking through an OrgDBOrgSetting, link here:  https://technet.microsoft.com/library/mt846659.aspx.

This is listed in the options list:
![image](https://user-images.githubusercontent.com/3036284/39594707-73f06950-4edb-11e8-8b29-767714307d0e.png)

But it looks like this has not been added to the settings.xml file in your managed solution.

Thanks for your help.

**Comment by seanmcne** [comment]
I just updated it yesterday - check the latest release on the releases page and try that.

**Comment by seanmcne** [comment]
https://github.com/seanmcne/OrgDbOrgSettings/releases/tag/v1.0.1805.0202

**Comment by justinwkruse** [comment]
Thanks for the quick follow-up Sean.  I double-checked I have the right release (I even uninstalled the managed solution and then reinstalled again from the latest release):
![image](https://user-images.githubusercontent.com/3036284/39600397-9cf55bba-4eec-11e8-8888-308a3b866eb1.png)

Here's the snippet from the tool in our environment:
![image](https://user-images.githubusercontent.com/3036284/39600519-f8120fb6-4eec-11e8-86dc-be9895a0c0ad.png)

In looking further at the settings.xml file (what you included in the source code), the TrackCategorizedItems is not listed <orgsetting> node.

Thanks again for the help.

**Comment by seanmcne** [comment]
My apologies and mistake, I did indeed miss this in the release yesterday!

**Comment by seanmcne** [comment]
Just got it added, checked in, built, and published as a release.  Thanks for the heads up!

**Comment by justinwkruse** [comment]
We're getting closer.  The setting shows up in the editor, but when I click on the Add button I get an error message:
![image](https://user-images.githubusercontent.com/3036284/39609443-f53c957a-4f16-11e8-94d5-189ed2613030.png)

Here's what the error specifies:

> We've handled an error, for reference the error info is:
> Name: Error
> Message:There was an error updating your orgDBOrgSettings: Invalid Organization Setting passed in. Please check the datatype and pass in an appropriate value. Description:Error Description Is Null
> stack:Error: There was an error updating your orgDBOrgSettings: Invalid Organization Setting passed in. Please check the datatype and pass in an appropriate value, at Object.

Perhaps there is something amiss with OrgDbOrgSettings Tool itself with this specific setting?

**Comment by justinwkruse** [comment]
v9 Spring Release
![image](https://user-images.githubusercontent.com/3036284/39610837-0bb34524-4f21-11e8-96e1-ea9a1e7839d0.png)

**Comment by seanmcne** [comment]
Interesting, I also just tested in a v9 org and mine does not work either - looks as if v9 doesn't include this setting yet or maybe there's a bug preventing it from working properly. 

![image](https://user-images.githubusercontent.com/2292260/39610863-df9dba80-4f18-11e8-80ba-7cd5c6565c54.png)
