### ISSUE TITLE
User authentication failed when using the CMD OrgDBOrg tool

### ISSUE THREAD

**Issue by siovchev0** [seanmcne/OrgDbOrgSettings#70]
I have followed the instructions found here: https://support.microsoft.com/en-us/topic/orgdborgsettings-tool-for-microsoft-dynamics-crm-20a10f46-2a24-a156-7144-365d49b842ba
-
IFD is setup and everything is working fine in regards to authentication to CRM.
-
I am receiving this error when trying to update an organization setting by using the command prompt tool:
![image](https://user-images.githubusercontent.com/69986439/113895410-9fce7980-97d1-11eb-859b-40cc8dede2c6.png)

**Comment by RedsGT** [comment]
The commandline tool is MS first party supported, while this project is not.  You'd be better off asking for help in the Dynamics Communities or opening a support ticket.  I have seen in the past that the cmd tool didn't like being forced to use TLS 1.2, so you could try using Fiddler as a TLS proxy to get past that issue.
