### ISSUE TITLE
Enable and disable Microsoft Teams Integration

### ISSUE THREAD

**Issue by timothybohte** [seanmcne/OrgDbOrgSettings#71]
It would be great to enable and disable Microsoft Teams Integration with custom entities in Dynamics 365.
One feature for enabling entities and one for disabling. In each feature we could state the entities we would like to enable/disable.
Here's more info about the codes needed: https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/integration-dev/teams-integration-using-code
Thanks in advance!

**Comment by RedsGT** [comment]
Was this meant https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell ?
