### ISSUE TITLE
Error message when trying to add action

### ISSUE THREAD

**Issue by MDaniels-inc** [seanmcne/OrgDbOrgSettings#76]
When trying to add the ActivateAdditionalRefreshofworkflowCondition action the error message, there was an error updating your dborgsettings not parsable was shown. This issue only occurred on the Production environment after successful testing on 2 other environments.
![orgdberror](https://user-images.githubusercontent.com/61021941/126624376-efaebee1-539f-419a-ba6a-da440399ef76.png)

**Comment by MDaniels-inc** [comment]
Fixed by using a Global Admin account

**Comment by seanmcne** [comment]
Hi, the ability to edit the "Organization" entity is generally reserved for system admins or users with a custom role enabling editing of the organization entity.  I would typically advise having the system administrator role in the org to run this (using the global admin role isn't necessary but having that would automatically grant you system admin in all environments which would unblock you as well).
