### ISSUE TITLE
Request to add max records download to Excel from portal

### ISSUE THREAD

**Issue by jcpieper** [seanmcne/OrgDbOrgSettings#80]
Hello!
Excited to find your tool allows 1,000,000 records to download to excel. Is there a way to do the same for records coming from the portal? The max is 5000, but I have users that need a max of 100,000 records.

**Comment by seanmcne** [comment]
I'm not entirely sure - if you can find the setting reference or where that setting exists for the portal I can look into it but I don't think it's and organization attribute or orgDBOrg setting.
