### ISSUE TITLE
Emails reappear in the queue

### ISSUE THREAD

**Issue by nevesmiguel** [seanmcne/OrgDbOrgSettings#84]
Hello,

We install this solution recently and change the option SSSCreateAdditionalQueueItemsForAlreadyTrackedEmail to TRUE.
This is because the users reported that some emails were not created in the queues.
After that, the users reported that some emails reappear in the queue as new ones.
You can see in the attached file the date when the email was created and the date when the reappear in the queue, and the related case:
![Queue_items](https://user-images.githubusercontent.com/2475009/158427161-80079a73-25ab-4377-b4b8-c9b2db95a54e.jpg)
Is possible that this change causes this behavior? Is this expected?

**Comment by seanmcne** [comment]
Thanks for reaching out!  Offhand I don't know the answer, I recommend opening a case (especially if you still have the case open where support had recommended enabling this setting) and asking for clarification from them.  

The only documentation I know for this would be found here: 
https://docs.microsoft.com/en-us/power-platform/admin/create-queue-items-from-synchronized-email-messages
