### ISSUE TITLE
Version 9.0.2.54

### ISSUE THREAD

**Issue by sykin** [seanmcne/OrgDbOrgSettings#9]
Hi,
Is there any eta on this tool being available for 9.0.2.54?

**not valid yet for v9.0.2.54 - will light up at build .0100 and higher for now, will adjust later if needed.**

**Comment by seanmcne** [comment]
Not sure what you mean, it's been available for 9.0.2.54 now since this release: https://github.com/seanmcne/OrgDbOrgSettings/releases/tag/v1.0.1805.0401 

the release notes refer to the bug/issue that was fixed #7 and #8
