### ISSUE TITLE
Can't change SSSTaskDeletionSyncBehaviorFromExchange

### ISSUE THREAD

**Issue by MassaOnGit** [seanmcne/OrgDbOrgSettings#98]
Hi, I get an error Message when I try to change SSSTaskDeletionSyncBehaviorFromExchange to 1 or 2.

![image](https://user-images.githubusercontent.com/91969907/210589703-afa08c5f-d6e4-4245-8b0e-28f7b06dd74c.png)

**Comment by seanmcne** [comment]
Min/Max values on the setting were blank - I'll update them to "0" and "2" to ensure the update can be validated correctly. Thanks for reporting!

**Comment by seanmcne** [comment]
Fixed in #99
